import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

/** 构建产物顶部的自动生成声明 */
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE.
Source code lives in the src directory.
*/`;

/** 当前是否执行生产构建 */
const isProduction = process.argv[2] === "production";

/** Obsidian 提供的外部运行时模块 */
const externalModules = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtinModules,
];

/** 插件的 esbuild 持续构建上下文 */
const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: externalModules,
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: isProduction ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: isProduction,
});

if (isProduction) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
